# Generated by Django 5.2.4 on 2025-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='码表ID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_comment='码', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_comment='类型', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_comment='名称', max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, db_comment='排序', null=True)),
            ],
            options={
                'db_table': 'sys_code',
                'db_table_comment': '码表（数据字典）',
            },
        ),
    ]
