# Generated by Django 5.2.4 on 2025-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='用户ID', primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, db_comment='账号', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_comment='密码', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, db_comment='昵称', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_comment='真实姓名', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_comment='手机号', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_comment='电子邮箱', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_comment='用户类型，0表示管理员，1表示教师，2表示学生', null=True)),
                ('avatar', models.BigIntegerField(blank=True, db_comment='头像ID，值为tb_image图片ID', null=True)),
                ('expired_time', models.DateTimeField(blank=True, db_comment='账号到期时间', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_comment='上一次登录时间', null=True)),
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'db_table_comment': '用户表',
                'managed': True,
            },
        ),
    ]
