# Generated by Django 5.2.4 on 2025-08-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_code_permission_role_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
