# Generated by Django 5.2.4 on 2025-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_remove_permissionrole_permission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_del',
            field=models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True),
        ),
    ]
