# Generated by Django 5.2.4 on 2025-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigIntegerField(db_comment='用户ID', primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, db_comment='账号', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_comment='密码', max_length=255, null=True)),
                ('salt', models.CharField(blank=True, db_comment='盐值', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, db_comment='昵称', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_comment='真实姓名', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_comment='手机号', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_comment='电子邮箱', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_comment='用户类型，0表示管理员，1表示教师，2表示学生', null=True)),
                ('avatar', models.BigIntegerField(blank=True, db_comment='头像ID，值为tb_image图片ID', null=True)),
                ('expired_time', models.DateTimeField(blank=True, db_comment='有效期', null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'db_table_comment': '用户表',
                'managed': False,
            },
        ),
    ]
