# Generated by Django 5.2.4 on 2025-08-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0004_delete_code_alter_user_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='教师ID', primary_key=True, serialize=False)),
                ('stu_friendly_name', models.CharField(blank=True, db_comment='师生称呼', max_length=100, null=True)),
                ('profession', models.IntegerField(blank=True, db_comment='职业, 如教师、教授等', null=True)),
                ('department', models.CharField(blank=True, db_comment='部门', max_length=100, null=True)),
                ('user_id', models.ForeignKey(db_comment='用户ID', on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
            options={
                'db_table': 'tb_teacher',
                'db_table_comment': '教师信息表',
            },
        ),
    ]
