# Generated by Django 5.2.4 on 2025-08-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_delete_code_alter_user_is_del'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='用户ID', null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
    ]
