# Generated by Django 5.2.4 on 2025-08-12 16:05

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='资源ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_comment='资源名称', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_comment='资源类型，0为图片，1为pdf...', null=True)),
                ('file', models.FileField(blank=True, db_comment='文件数据', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='eaa'), upload_to=django_minio_backend.models.iso_date_prefix)),
                ('size', models.BigIntegerField(blank=True, db_comment='文件大小', null=True)),
                ('group_name', models.CharField(blank=True, db_comment='文件组名', max_length=255, null=True)),
                ('remote_file_url', models.CharField(blank=True, db_comment='远程文件路径', max_length=255, null=True)),
                ('old_filename', models.CharField(blank=True, db_comment='源文件名', max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, db_comment='同层级排序', null=True)),
            ],
            options={
                'db_table': 'sys_resource',
                'db_table_comment': '文件资源表',
            },
        ),
    ]
