# Generated by Django 5.2.4 on 2025-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.BigIntegerField(blank=True, db_comment='文件大小（Bytes）', null=True),
        ),
    ]
