# Generated by Django 5.2.4 on 2025-08-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0004_delete_code_alter_user_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='学生ID', primary_key=True, serialize=False)),
                ('identity', models.IntegerField(blank=True, db_comment='学生身份, 0表示小学，1表示初中，2表示高中，3表示大学， 4表示硕士研究生，5表示博士研究生, 6表示其他', null=True)),
                ('student_no', models.CharField(blank=True, db_comment='学号', max_length=32, null=True)),
                ('school_no', models.CharField(blank=True, db_comment='学校编号', max_length=32, null=True)),
                ('enrollment', models.DateField(blank=True, db_comment='入学日期', null=True)),
                ('birth_date', models.DateField(blank=True, db_comment='出生日期', null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女')], db_comment='性别', null=True)),
                ('address', models.CharField(blank=True, db_comment='现住址', max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, '在读'), (1, '休学'), (2, '毕业'), (3, '退学')], db_comment='学生状态', default=0, null=True)),
                ('remark', models.TextField(blank=True, db_comment='备注', null=True)),
                ('user', models.ForeignKey(blank=True, db_comment='用户ID', null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
            options={
                'db_table': 'tb_student',
                'db_table_comment': '学生信息表',
                'ordering': ['-create_time'],
            },
        ),
    ]
