# Generated by Django 5.2.4 on 2025-08-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0003_remove_permissionrole_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='权限ID', primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField(blank=True, db_comment='父级权限ID', null=True)),
                ('key', models.CharField(blank=True, db_comment='权限码（权限路径）', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_comment='权限类型，0表示页面权限，1表示操作权限', null=True)),
                ('name', models.CharField(blank=True, db_comment='权限名', max_length=255, null=True)),
                ('grade', models.IntegerField(blank=True, db_comment='目录层级', null=True)),
                ('des', models.CharField(blank=True, db_comment='描述', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_permission',
                'db_table_comment': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='角色ID', primary_key=True, serialize=False)),
                ('role_key', models.CharField(blank=True, db_comment='角色码', max_length=255, null=True)),
                ('role_name', models.CharField(blank=True, db_comment='角色名称', max_length=255, null=True)),
                ('des', models.CharField(blank=True, db_comment='描述', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_comment='角色类型，0可选，1特殊，2用户自定义', null=True)),
            ],
            options={
                'db_table': 'sys_role',
                'db_table_comment': '角色表',
            },
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='ID', primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(db_column='permission_id', db_comment='外键，sys_permission权限ID', on_delete=django.db.models.deletion.RESTRICT, to='permission.permission')),
                ('role', models.ForeignKey(db_column='role_id', db_comment='外键，sys_role角色ID', on_delete=django.db.models.deletion.RESTRICT, to='permission.role')),
            ],
            options={
                'db_table': 'sys_permission_role',
                'db_table_comment': '权限角色表',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='ID', primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_column='role_id', db_comment='外键，sys_role角色ID', on_delete=django.db.models.deletion.RESTRICT, to='permission.role')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='外键，sys_user用户ID', on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
            options={
                'db_table': 'sys_user_role',
                'db_table_comment': '用户角色关联表',
            },
        ),
    ]
